/**
 * src/strings.js
 * ==============
 * Language data for the panel UI — English / French / German / Italian.
 *
 * This file contains ONLY data (no logic). To add a language:
 *   1. Copy the "en" block.
 *   2. Rename it with the 2-letter ISO code (e.g. "es").
 *   3. Translate every value. Placeholders like {count} must be kept as-is.
 *
 * Lookup logic lives in src/i18n.js. Missing keys fall back to English.
 *
 * Copyright (C) 2025-2026 SZH/CSPS — Swiss Centre for Special Needs Education
 * Licensed under GNU GPL v3 — https://www.gnu.org/licenses/
 */

"use strict";

module.exports = {

  // ─── English ───────────────────────────────────────────────────────────────
  en: {

    // Empty states / errors
    noDocument:             "No document open.",
    noArticles:             "No articles defined. Configure the Articles panel (Window > Articles) first.",
    noPage:                 "No active page.",
    noSelection:            "Select at least 1 object.",
    errGeneric:             "Error: {msg}",
    busyWorking:            "Processing…",
    busyDrawing:            "Drawing control layer… (this can take a moment)",

    // Preview section
    previewTitle:           "Page preview",
    previewPageLabel:       "Page {name}",
    previewToggleTitle:     "Hide/show preview",
    btnPreviewTag:          "Tag RO (articles)",
    btnPreviewConstruction: "Construction RO (layers)",
    previewHintTag:         "Numbers follow the Articles panel order (Tag RO). Artifacts are hidden.",
    previewHintConstruction:"Numbers follow the layer stack from bottom to top (Construction RO). Artifacts are hidden.",
    previewNoArticles:      "No Tag RO / article defined — nothing to display.",
    previewNoItemsTag:      "No Tag RO item on this page. Add the objects to an article (Articles panel) or use \"Reorder selection\".",
    previewNoItemsConstruction: "No visible object on this page.",

    // Navigation section
    navTitle:               "Navigate",
    navPrev:                "← Previous",
    navNext:                "Next →",
    navCurrent:             "{current} / {total}",
    navItem:                "#{num} — {name}",
    navArticle:             "Article: {name}",
    navLayer:               "Layer: {name}",
    navSelectHint:          "Object selected in document.",
    navNoItems:             "No items on this page.",
    navAlt:                 "Alt: {text}",
    navAltMissing:          "⚠ Missing alt text",

    // Control layers section
    overlayTitle:           "Control layers (in document)",
    tipOverlaySection:      "Draws locked, semi-transparent control layers in the document to verify the reading orders: [Tag RO] in red, [Construction RO] in blue. Pick the scope (active page or all pages), then Show/Clear each layer. Delete the control layers before the final export.",
    scopeActivePage:        "Active page",
    scopeAllPages:          "All pages (slower)",
    btnShow:                "Show",
    btnClear:               "Clear",
    layerDrawn:             "Overlay drawn: {count} object(s).",
    layerDeleted:           "Overlay layer deleted.",
    layerNotFound:          "Overlay layer not found.",

    // Reorder & groups section
    fastTitle:              "Reorder & groups",
    fastIntro:              "A group is a single block in the reading order: to reorder elements inside a group, ungroup first. Buttons 1 and 4 save and then rebuild the groups.",
    btnFastReorder:         "3) Reorder selection",
    btnAlignZOrder:         "Align Construction RO to Tag RO (experimental)",
    btnFastSaveGroups:      "1) Save groups",
    btnFastUngroupAll:      "2) Ungroup all",
    btnFastRegroup:         "4) Re-group from save",
    fastNoSelection:        "Select at least 2 objects.",
    fastSingleTarget:       "Selection resolves to a single object/group. Select at least 2 independent objects.",
    fastReordered:          "Reordered {count} object(s).",
    fastReorderSkipped:     "Some objects were skipped (different parent/layer or unsupported type).",
    fastGroupsSaved:        "Saved {count} group(s).",
    fastNoGroupsSaved:      "No saved groups for this document.",
    fastUngrouped:          "Ungrouped {count} group(s).",
    fastRegrouped:          "Re-grouped {count} group(s).",
    alignDone:              "{count} object(s) re-stacked to match the Tag RO.",
    alignLayersWarning:     "Note: items span several layers; the order between layers still follows the layer stack.",
    articleCreated:         "Article \"{name}\" created with {count} object(s).",
    articleMembersAdded:    "{count} object(s) added to article \"{name}\".",

    // Artifacts & alt text sections
    artifactTitle:          "Artifacts",
    artifactPreviewTitle:   "Artifact preview",
    altTextTitle:           "Alt text",
    markupTitle:            "HTML markup",
    btnSetArtifact:         "Set as artifact",
    btnUnsetArtifact:       "Remove artifact tag",
    btnToggleArtifacts:     "Hide/show artifacts",
    btnMoveArtifacts:       "Move artifacts to [Artifacts] layer",
    btnRestoreArtifacts:    "Restore artifacts to original layers",
    btnShowAltText:         "Show alt texts",
    btnHideAltText:         "Hide alt texts",
    btnEditAltText:         "Edit alt text",
    btnShowMarkup:          "Show HTML markup",
    btnHideMarkup:          "Hide HTML markup",
    altEditSave:            "Save",
    altEditCancel:          "Cancel",
    altEditApplied:         "Alt text saved.",
    altEditArtifactRemoved: "The artifact tag was removed so the alt text can be read.",
    altEditNoTarget:        "Select an object in the document first.",
    markupDrawn:            "[Markup] layer drawn: {count} paragraph(s).",
    markupDeleted:          "[Markup] layer deleted.",
    artifactHint:           "Artifacts are excluded from every reading order and hidden in the previews.",
    artifactsSet:           "{count} object(s) tagged as artifact.",
    artifactsUnset:         "Artifact tag removed from {count} object(s).",
    artifactsHidden:        "{count} artifact(s) hidden.",
    artifactsShown:         "{count} artifact(s) shown.",
    artifactsNone:          "No artifacts in this document.",
    artifactsMoved:         "{count} artifact(s) moved to [Artifacts].",
    artifactsMoveSkipped:   "{count} skipped (inside a group — ungroup first).",
    artifactsRestored:      "{count} artifact(s) restored to their original layer.",
    artifactsNoMoves:       "Nothing to restore for this document.",
    altTextDrawn:           "[Alt Text] layer drawn: {count} image(s), {missing} missing alt text.",
    altTextDeleted:         "[Alt Text] layer deleted.",
    altMissing:             "MISSING ALT",
    altDecorative:          "Decorative",
    altExternal:            "Alt ({source})",

    // Language switcher & about
    langTitle:              "Plugin language",
    langAuto:               "Auto (InDesign language)",
    aboutTitle:             "About",
    aboutText:              "This tool helps build and verify the two reading orders of an accessible PDF: the Tag RO (Articles panel order, required by PDF/UA, followed by conformant screen readers) and the Construction RO (layer stacking order, read bottom-up, followed by reflow and simple readers). Suggested workflow: 1. check the preview page by page · 2. reorder the selection (ungroup first if needed) · 3. tag artifacts and fill in alt texts · 4. verify with the control layers, then delete them before export. Developed by SZH/CSPS with AI assistance.",

    // Tooltips
    tipPreviewTag:          "Preview the reading order from the Articles panel (what conformant screen readers follow).",
    tipPreviewConstruction: "Preview the layer-stack order, read bottom-up (what reflow and simple readers follow).",
    tipNavPrev:             "Select the previous item in the reading order.",
    tipNavNext:             "Select the next item in the reading order.",
    tipFastReorder:         "Step 3 — also usable on its own: Shift-click the objects in the desired reading order (first clicked = read first), then click here. The layer stack and the Articles panel are updated to match.",
    tipAlignZOrder:         "No selection needed: re-stacks every article item so the Construction RO matches the Tag RO. May change overlapping visuals — check the page afterwards.",
    tipSaveGroups:          "Step 1 of the group workflow: memorize the current groups before ungrouping (this document, this session only).",
    tipUngroupAll:          "Step 2: ungroup everything so each object can be reordered individually (a group is a single block in the reading order).",
    tipRegroup:             "Step 4, after reordering: rebuilds the groups exactly as saved in step 1.",
    tipSetArtifact:         "Tag the selection as artifact: excluded from the structure and from every reading order.",
    tipUnsetArtifact:       "Reset the selection's export tag to 'Based on Object'.",
    tipToggleArtifacts:     "Hide or show every artifact in the document.",
    tipMoveArtifacts:       "Move all top-level artifacts to the [Artifacts] layer, keeping their stacking order.",
    tipRestoreArtifacts:    "Move artifacts back to the layers they came from.",
    tipEditAltText:         "Edit the alt text of the selected object, right here in the panel.",
    tipToggleAltText:       "Draw/delete the [Alt Text] layer: each image labelled with its alt text, missing ones flagged in red.",
    tipToggleMarkup:        "Draw/delete the [Markup] layer: each paragraph labelled with its PDF export tag (<P> by default)."
  },

  // ─── Français ──────────────────────────────────────────────────────────────
  fr: {

    // États vides / erreurs
    noDocument:             "Aucun document ouvert.",
    noArticles:             "Aucun article défini. Configurez d'abord le panneau Articles (Fenêtre > Articles).",
    noPage:                 "Aucune page active.",
    noSelection:            "Sélectionnez au moins 1 objet.",
    errGeneric:             "Erreur : {msg}",
    busyWorking:            "Traitement en cours…",
    busyDrawing:            "Construction du calque de contrôle… (cela peut prendre un moment)",

    // Section aperçu
    previewTitle:           "Aperçu de la page",
    previewPageLabel:       "Page {name}",
    previewToggleTitle:     "Masquer/afficher l'aperçu",
    btnPreviewTag:          "Tag RO (articles)",
    btnPreviewConstruction: "Construction RO (layers)",
    previewHintTag:         "Les numéros suivent l'ordre du panneau Articles (Tag RO). Les artifacts sont masqués.",
    previewHintConstruction:"Les numéros suivent la pile des calques, de bas en haut (Construction RO). Les artifacts sont masqués.",
    previewNoArticles:      "Aucun Tag RO / article défini — rien à afficher.",
    previewNoItemsTag:      "Aucun élément du Tag RO sur cette page. Ajoutez les objets à un article (panneau Articles) ou utilisez « Réordonner la sélection ».",
    previewNoItemsConstruction: "Aucun objet visible sur cette page.",

    // Section navigation
    navTitle:               "Navigation",
    navPrev:                "← Précédent",
    navNext:                "Suivant →",
    navCurrent:             "{current} / {total}",
    navItem:                "#{num} — {name}",
    navArticle:             "Article : {name}",
    navLayer:               "Calque : {name}",
    navSelectHint:          "Objet sélectionné dans le document.",
    navNoItems:             "Aucun élément sur cette page.",
    navAlt:                 "Alt : {text}",
    navAltMissing:          "⚠ Texte alternatif manquant",

    // Section calques de contrôle
    overlayTitle:           "Calques de contrôle (dans le document)",
    tipOverlaySection:      "Dessine des calques de contrôle verrouillés et semi-transparents dans le document pour vérifier les ordres de lecture : [Tag RO] en rouge, [Construction RO] en bleu. Choisissez l'étendue (page active ou toutes les pages), puis Afficher/Effacer chaque calque. Supprimez les calques de contrôle avant l'export final.",
    scopeActivePage:        "Page active",
    scopeAllPages:          "Toutes les pages (plus lent)",
    btnShow:                "Afficher",
    btnClear:               "Effacer",
    layerDrawn:             "Calque dessiné : {count} objet(s).",
    layerDeleted:           "Calque supprimé.",
    layerNotFound:          "Calque introuvable.",

    // Section réordonner & groupes
    fastTitle:              "Réordonner & groupes",
    fastIntro:              "Un groupe est un bloc unique dans l'ordre de lecture : pour réordonner des éléments à l'intérieur d'un groupe, il faut d'abord le dégrouper. Les boutons 1 et 4 sauvegardent puis reconstruisent les groupes.",
    btnFastReorder:         "3) Réordonner la sélection",
    btnAlignZOrder:         "Aligner Construction RO sur Tag RO (expérimental)",
    btnFastSaveGroups:      "1) Sauvegarder les groupes",
    btnFastUngroupAll:      "2) Tout dégrouper",
    btnFastRegroup:         "4) Regrouper selon la sauvegarde",
    fastNoSelection:        "Sélectionnez au moins 2 objets.",
    fastSingleTarget:       "La sélection se réduit à un seul objet/groupe. Sélectionnez au moins 2 objets indépendants.",
    fastReordered:          "{count} objet(s) réordonné(s).",
    fastReorderSkipped:     "Certains objets ont été ignorés (parent/calque différent ou type non pris en charge).",
    fastGroupsSaved:        "{count} groupe(s) sauvegardé(s).",
    fastNoGroupsSaved:      "Aucun groupe sauvegardé pour ce document.",
    fastUngrouped:          "{count} groupe(s) dissocié(s).",
    fastRegrouped:          "{count} groupe(s) regroupé(s).",
    alignDone:              "{count} objet(s) réempilé(s) selon le Tag RO.",
    alignLayersWarning:     "Note : les objets sont répartis sur plusieurs calques ; l'ordre entre calques reste celui de la pile.",
    articleCreated:         "Article « {name} » créé avec {count} objet(s).",
    articleMembersAdded:    "{count} objet(s) ajouté(s) à l'article « {name} ».",

    // Sections artifacts & textes alternatifs
    artifactTitle:          "Artifacts",
    artifactPreviewTitle:   "Aperçu des artifacts",
    altTextTitle:           "Textes alternatifs",
    markupTitle:            "Balisage HTML",
    btnSetArtifact:         "Définir comme artifact",
    btnUnsetArtifact:       "Retirer le balisage artifact",
    btnToggleArtifacts:     "Cacher/afficher les artifacts",
    btnMoveArtifacts:       "Déplacer les artifacts sur le calque [Artifacts]",
    btnRestoreArtifacts:    "Restaurer les calques d'origine",
    btnShowAltText:         "Afficher les textes alternatifs",
    btnHideAltText:         "Masquer les textes alternatifs",
    btnEditAltText:         "Modifier le texte alternatif",
    btnShowMarkup:          "Afficher le balisage HTML",
    btnHideMarkup:          "Masquer le balisage HTML",
    altEditSave:            "Enregistrer",
    altEditCancel:          "Annuler",
    altEditApplied:         "Texte alternatif enregistré.",
    altEditArtifactRemoved: "Le balisage artifact a été retiré pour que le texte alternatif soit lu.",
    altEditNoTarget:        "Sélectionnez d'abord un objet dans le document.",
    markupDrawn:            "Calque [Markup] dessiné : {count} paragraphe(s).",
    markupDeleted:          "Calque [Markup] supprimé.",
    artifactHint:           "Les artifacts sont exclus de tous les ordres de lecture et masqués dans les aperçus.",
    artifactsSet:           "{count} objet(s) défini(s) comme artifact.",
    artifactsUnset:         "Balisage artifact retiré de {count} objet(s).",
    artifactsHidden:        "{count} artifact(s) masqué(s).",
    artifactsShown:         "{count} artifact(s) affiché(s).",
    artifactsNone:          "Aucun artifact dans ce document.",
    artifactsMoved:         "{count} artifact(s) déplacé(s) sur [Artifacts].",
    artifactsMoveSkipped:   "{count} ignoré(s) (dans un groupe — dégroupez d'abord).",
    artifactsRestored:      "{count} artifact(s) restauré(s) sur leur calque d'origine.",
    artifactsNoMoves:       "Rien à restaurer pour ce document.",
    altTextDrawn:           "Calque [Alt Text] dessiné : {count} image(s), {missing} sans texte alternatif.",
    altTextDeleted:         "Calque [Alt Text] supprimé.",
    altMissing:             "ALT MANQUANT",
    altDecorative:          "Décoratif",
    altExternal:            "Alt ({source})",

    // Sélecteur de langue & à propos
    langTitle:              "Langue du plugin",
    langAuto:               "Auto (langue d'InDesign)",
    aboutTitle:             "À propos",
    aboutText:              "Cet outil aide à construire et vérifier les deux ordres de lecture d'un PDF accessible : le Tag RO (ordre du panneau Articles, exigé par PDF/UA, suivi par les lecteurs d'écran conformes) et la Construction RO (ordre d'empilement des calques, lu de bas en haut, suivi par le reflow et les lecteurs simples). Démarche conseillée : 1. contrôler l'aperçu page par page · 2. réordonner la sélection (dégrouper d'abord si nécessaire) · 3. baliser les artifacts et compléter les textes alternatifs · 4. vérifier avec les calques de contrôle, puis les supprimer avant l'export. Développé par le SZH/CSPS avec le soutien de l'IA.",

    // Infobulles
    tipPreviewTag:          "Aperçu de l'ordre de lecture du panneau Articles (suivi par les lecteurs d'écran conformes).",
    tipPreviewConstruction: "Aperçu de l'ordre de la pile des calques, lu de bas en haut (suivi par le reflow et les lecteurs simples).",
    tipNavPrev:             "Sélectionne l'élément précédent de l'ordre de lecture.",
    tipNavNext:             "Sélectionne l'élément suivant de l'ordre de lecture.",
    tipFastReorder:         "Étape 3 — utilisable aussi seule : cliquez les objets avec Maj dans l'ordre de lecture voulu (premier cliqué = lu en premier), puis cliquez ici. La pile des calques et le panneau Articles sont mis à jour.",
    tipAlignZOrder:         "Aucune sélection nécessaire : réempile tous les éléments d'articles pour que la Construction RO suive le Tag RO. Peut modifier les superpositions visuelles — vérifiez la page ensuite.",
    tipSaveGroups:          "Étape 1 du travail avec groupes : mémorise les groupes actuels avant de dégrouper (ce document, cette session uniquement).",
    tipUngroupAll:          "Étape 2 : dégroupe tout pour réordonner chaque objet individuellement (un groupe est un bloc unique dans l'ordre de lecture).",
    tipRegroup:             "Étape 4, après le réordonnancement : reconstruit les groupes exactement comme sauvegardés à l'étape 1.",
    tipSetArtifact:         "Balise la sélection comme artifact : exclue de la structure et de tous les ordres de lecture.",
    tipUnsetArtifact:       "Rétablit l'option d'export « D'après l'objet » sur la sélection.",
    tipToggleArtifacts:     "Masque ou affiche tous les artifacts du document.",
    tipMoveArtifacts:       "Déplace les artifacts de premier niveau sur le calque [Artifacts], en conservant leur ordre d'empilement.",
    tipRestoreArtifacts:    "Replace les artifacts sur leur calque d'origine.",
    tipEditAltText:         "Modifie le texte alternatif de l'objet sélectionné, directement dans le panneau.",
    tipToggleAltText:       "Dessine/supprime le calque [Alt Text] : chaque image étiquetée avec son texte alternatif, manquants signalés en rouge.",
    tipToggleMarkup:        "Dessine/supprime le calque [Markup] : chaque paragraphe étiqueté avec sa balise d'export PDF (<P> par défaut)."
  },

  // ─── Deutsch ───────────────────────────────────────────────────────────────
  de: {

    // Leere Zustände / Fehler
    noDocument:             "Kein Dokument geöffnet.",
    noArticles:             "Keine Artikel definiert. Zuerst das Artikel-Bedienfeld konfigurieren (Fenster > Artikel).",
    noPage:                 "Keine aktive Seite.",
    noSelection:            "Mindestens 1 Objekt auswählen.",
    errGeneric:             "Fehler: {msg}",
    busyWorking:            "Verarbeitung läuft…",
    busyDrawing:            "Kontroll-Ebene wird gezeichnet… (kann einen Moment dauern)",

    // Vorschau
    previewTitle:           "Seitenvorschau",
    previewPageLabel:       "Seite {name}",
    previewToggleTitle:     "Vorschau ein-/ausblenden",
    btnPreviewTag:          "Tag RO (Artikel)",
    btnPreviewConstruction: "Construction RO (Ebenen)",
    previewHintTag:         "Die Nummern folgen der Reihenfolge des Artikel-Bedienfelds (Tag RO). Artefakte sind ausgeblendet.",
    previewHintConstruction:"Die Nummern folgen dem Ebenenstapel von unten nach oben (Construction RO). Artefakte sind ausgeblendet.",
    previewNoArticles:      "Kein Tag RO / Artikel definiert — nichts anzuzeigen.",
    previewNoItemsTag:      "Kein Tag-RO-Element auf dieser Seite. Objekte einem Artikel hinzufügen (Artikel-Bedienfeld) oder «Auswahl umordnen» verwenden.",
    previewNoItemsConstruction: "Kein sichtbares Objekt auf dieser Seite.",

    // Navigation
    navTitle:               "Navigation",
    navPrev:                "← Zurück",
    navNext:                "Weiter →",
    navCurrent:             "{current} / {total}",
    navItem:                "#{num} — {name}",
    navArticle:             "Artikel: {name}",
    navLayer:               "Ebene: {name}",
    navSelectHint:          "Objekt im Dokument ausgewählt.",
    navNoItems:             "Keine Elemente auf dieser Seite.",
    navAlt:                 "Alt: {text}",
    navAltMissing:          "⚠ Alternativtext fehlt",

    // Kontroll-Ebenen
    overlayTitle:           "Kontroll-Ebenen (im Dokument)",
    tipOverlaySection:      "Zeichnet gesperrte, halbtransparente Kontroll-Ebenen ins Dokument zur Prüfung der Lesereihenfolgen: [Tag RO] in Rot, [Construction RO] in Blau. Umfang wählen (aktive Seite oder alle Seiten), dann Ebene anzeigen/entfernen. Vor dem finalen Export löschen.",
    scopeActivePage:        "Aktive Seite",
    scopeAllPages:          "Alle Seiten (langsamer)",
    btnShow:                "Anzeigen",
    btnClear:               "Entfernen",
    layerDrawn:             "Ebene gezeichnet: {count} Objekt(e).",
    layerDeleted:           "Ebene gelöscht.",
    layerNotFound:          "Ebene nicht gefunden.",

    // Umordnen & Gruppen
    fastTitle:              "Umordnen & Gruppen",
    fastIntro:              "Eine Gruppe ist ein einziger Block in der Lesereihenfolge: Um Elemente innerhalb einer Gruppe umzuordnen, muss sie zuerst aufgelöst werden. Die Schaltflächen 1 und 4 speichern die Gruppen und stellen sie wieder her.",
    btnFastReorder:         "3) Auswahl umordnen",
    btnAlignZOrder:         "Construction RO an Tag RO angleichen (experimentell)",
    btnFastSaveGroups:      "1) Gruppen speichern",
    btnFastUngroupAll:      "2) Alle Gruppen auflösen",
    btnFastRegroup:         "4) Gruppen wiederherstellen",
    fastNoSelection:        "Mindestens 2 Objekte auswählen.",
    fastSingleTarget:       "Die Auswahl ergibt nur ein Objekt/eine Gruppe. Mindestens 2 unabhängige Objekte auswählen.",
    fastReordered:          "{count} Objekt(e) umgeordnet.",
    fastReorderSkipped:     "Einige Objekte wurden übersprungen (anderes Elternelement/andere Ebene oder nicht unterstützter Typ).",
    fastGroupsSaved:        "{count} Gruppe(n) gespeichert.",
    fastNoGroupsSaved:      "Keine gespeicherten Gruppen für dieses Dokument.",
    fastUngrouped:          "{count} Gruppe(n) aufgelöst.",
    fastRegrouped:          "{count} Gruppe(n) wiederhergestellt.",
    alignDone:              "{count} Objekt(e) gemäss Tag RO neu gestapelt.",
    alignLayersWarning:     "Hinweis: Die Objekte liegen auf mehreren Ebenen; die Reihenfolge zwischen Ebenen folgt weiterhin dem Ebenenstapel.",
    articleCreated:         "Artikel «{name}» mit {count} Objekt(en) erstellt.",
    articleMembersAdded:    "{count} Objekt(e) zum Artikel «{name}» hinzugefügt.",

    // Artefakte & Alternativtexte
    artifactTitle:          "Artefakte",
    artifactPreviewTitle:   "Artefakt-Vorschau",
    altTextTitle:           "Alternativtexte",
    markupTitle:            "HTML-Auszeichnung",
    btnSetArtifact:         "Als Artefakt definieren",
    btnUnsetArtifact:       "Artefakt-Tag entfernen",
    btnToggleArtifacts:     "Artefakte aus-/einblenden",
    btnMoveArtifacts:       "Artefakte auf Ebene [Artifacts] verschieben",
    btnRestoreArtifacts:    "Ursprüngliche Ebenen wiederherstellen",
    btnShowAltText:         "Alternativtexte einblenden",
    btnHideAltText:         "Alternativtexte ausblenden",
    btnEditAltText:         "Alternativtext bearbeiten",
    btnShowMarkup:          "HTML-Auszeichnung einblenden",
    btnHideMarkup:          "HTML-Auszeichnung ausblenden",
    altEditSave:            "Speichern",
    altEditCancel:          "Abbrechen",
    altEditApplied:         "Alternativtext gespeichert.",
    altEditArtifactRemoved: "Das Artefakt-Tag wurde entfernt, damit der Alternativtext gelesen wird.",
    altEditNoTarget:        "Zuerst ein Objekt im Dokument auswählen.",
    markupDrawn:            "Ebene [Markup] gezeichnet: {count} Absatz/Absätze.",
    markupDeleted:          "Ebene [Markup] gelöscht.",
    artifactHint:           "Artefakte sind von allen Lesereihenfolgen ausgeschlossen und in den Vorschauen ausgeblendet.",
    artifactsSet:           "{count} Objekt(e) als Artefakt definiert.",
    artifactsUnset:         "Artefakt-Tag von {count} Objekt(en) entfernt.",
    artifactsHidden:        "{count} Artefakt(e) ausgeblendet.",
    artifactsShown:         "{count} Artefakt(e) eingeblendet.",
    artifactsNone:          "Keine Artefakte in diesem Dokument.",
    artifactsMoved:         "{count} Artefakt(e) auf [Artifacts] verschoben.",
    artifactsMoveSkipped:   "{count} übersprungen (innerhalb einer Gruppe — zuerst Gruppe auflösen).",
    artifactsRestored:      "{count} Artefakt(e) auf ihre ursprüngliche Ebene zurückgesetzt.",
    artifactsNoMoves:       "Nichts wiederherzustellen für dieses Dokument.",
    altTextDrawn:           "Ebene [Alt Text] gezeichnet: {count} Bild(er), {missing} ohne Alternativtext.",
    altTextDeleted:         "Ebene [Alt Text] gelöscht.",
    altMissing:             "ALT FEHLT",
    altDecorative:          "Dekorativ",
    altExternal:            "Alt ({source})",

    // Sprachauswahl & Info
    langTitle:              "Sprache des Plugins",
    langAuto:               "Auto (InDesign-Sprache)",
    aboutTitle:             "Über",
    aboutText:              "Dieses Werkzeug hilft, die beiden Lesereihenfolgen eines barrierefreien PDFs aufzubauen und zu prüfen: die Tag RO (Reihenfolge des Artikel-Bedienfelds, von PDF/UA verlangt, von konformen Screenreadern befolgt) und die Construction RO (Stapelreihenfolge der Ebenen, von unten nach oben gelesen, von Reflow und einfachen Readern befolgt). Empfohlenes Vorgehen: 1. Vorschau Seite für Seite prüfen · 2. Auswahl umordnen (bei Bedarf zuerst Gruppen auflösen) · 3. Artefakte markieren und Alternativtexte ergänzen · 4. mit den Kontroll-Ebenen prüfen und diese vor dem Export löschen. Entwickelt vom SZH/CSPS mit KI-Unterstützung.",

    // Tooltips
    tipPreviewTag:          "Vorschau der Lesereihenfolge des Artikel-Bedienfelds (von konformen Screenreadern befolgt).",
    tipPreviewConstruction: "Vorschau der Ebenenstapel-Reihenfolge, von unten nach oben gelesen (von Reflow und einfachen Readern befolgt).",
    tipNavPrev:             "Wählt das vorherige Element der Lesereihenfolge aus.",
    tipNavNext:             "Wählt das nächste Element der Lesereihenfolge aus.",
    tipFastReorder:         "Schritt 3 — auch allein verwendbar: Objekte mit Umschalt-Klick in der gewünschten Lesereihenfolge auswählen (zuerst angeklickt = zuerst gelesen), dann hier klicken. Ebenenstapel und Artikel-Bedienfeld werden angepasst.",
    tipAlignZOrder:         "Keine Auswahl nötig: stapelt alle Artikel-Elemente neu, damit die Construction RO dem Tag RO folgt. Kann sichtbare Überlappungen verändern — Seite danach prüfen.",
    tipSaveGroups:          "Schritt 1 des Gruppen-Workflows: merkt sich die aktuellen Gruppen vor dem Auflösen (dieses Dokument, nur diese Sitzung).",
    tipUngroupAll:          "Schritt 2: löst alle Gruppen auf, damit jedes Objekt einzeln umgeordnet werden kann (eine Gruppe ist ein einziger Block in der Lesereihenfolge).",
    tipRegroup:             "Schritt 4, nach dem Umordnen: stellt die Gruppen genau wie in Schritt 1 gespeichert wieder her.",
    tipSetArtifact:         "Markiert die Auswahl als Artefakt: von der Struktur und allen Lesereihenfolgen ausgeschlossen.",
    tipUnsetArtifact:       "Setzt die Export-Option der Auswahl auf «Anhand des Objekts» zurück.",
    tipToggleArtifacts:     "Blendet alle Artefakte des Dokuments aus oder ein.",
    tipMoveArtifacts:       "Verschiebt alle Artefakte auf die Ebene [Artifacts] und erhält ihre Stapelreihenfolge.",
    tipRestoreArtifacts:    "Verschiebt die Artefakte zurück auf ihre ursprünglichen Ebenen.",
    tipEditAltText:         "Bearbeitet den Alternativtext des ausgewählten Objekts direkt im Bedienfeld.",
    tipToggleAltText:       "Zeichnet/löscht die Ebene [Alt Text]: jedes Bild mit seinem Alternativtext beschriftet, fehlende rot markiert.",
    tipToggleMarkup:        "Zeichnet/löscht die Ebene [Markup]: jeder Absatz mit seinem PDF-Export-Tag beschriftet (<P> als Standard)."
  },

  // ─── Italiano ──────────────────────────────────────────────────────────────
  it: {

    // Stati vuoti / errori
    noDocument:             "Nessun documento aperto.",
    noArticles:             "Nessun articolo definito. Configurare prima il pannello Articoli (Finestra > Articoli).",
    noPage:                 "Nessuna pagina attiva.",
    noSelection:            "Selezionare almeno 1 oggetto.",
    errGeneric:             "Errore: {msg}",
    busyWorking:            "Elaborazione in corso…",
    busyDrawing:            "Costruzione del livello di controllo… (può richiedere un momento)",

    // Sezione anteprima
    previewTitle:           "Anteprima pagina",
    previewPageLabel:       "Pagina {name}",
    previewToggleTitle:     "Mostra/nascondi anteprima",
    btnPreviewTag:          "Tag RO (articoli)",
    btnPreviewConstruction: "Construction RO (livelli)",
    previewHintTag:         "I numeri seguono l'ordine del pannello Articoli (Tag RO). Gli artefatti sono nascosti.",
    previewHintConstruction:"I numeri seguono la pila dei livelli dal basso verso l'alto (Construction RO). Gli artefatti sono nascosti.",
    previewNoArticles:      "Nessun Tag RO / articolo definito — niente da visualizzare.",
    previewNoItemsTag:      "Nessun elemento del Tag RO in questa pagina. Aggiungere gli oggetti a un articolo (pannello Articoli) o usare \"Riordina la selezione\".",
    previewNoItemsConstruction: "Nessun oggetto visibile in questa pagina.",

    // Sezione navigazione
    navTitle:               "Navigazione",
    navPrev:                "← Precedente",
    navNext:                "Successivo →",
    navCurrent:             "{current} / {total}",
    navItem:                "#{num} — {name}",
    navArticle:             "Articolo: {name}",
    navLayer:               "Livello: {name}",
    navSelectHint:          "Oggetto selezionato nel documento.",
    navNoItems:             "Nessun elemento in questa pagina.",
    navAlt:                 "Alt: {text}",
    navAltMissing:          "⚠ Testo alternativo mancante",

    // Sezione livelli di controllo
    overlayTitle:           "Livelli di controllo (nel documento)",
    tipOverlaySection:      "Disegna livelli di controllo bloccati e semitrasparenti nel documento per verificare gli ordini di lettura: [Tag RO] in rosso, [Construction RO] in blu. Scegliere l'ambito (pagina attiva o tutte le pagine), poi Mostra/Rimuovi ogni livello. Eliminare i livelli di controllo prima dell'esportazione finale.",
    scopeActivePage:        "Pagina attiva",
    scopeAllPages:          "Tutte le pagine (più lento)",
    btnShow:                "Mostra",
    btnClear:               "Rimuovi",
    layerDrawn:             "Livello disegnato: {count} oggetto/i.",
    layerDeleted:           "Livello eliminato.",
    layerNotFound:          "Livello non trovato.",

    // Sezione riordino e gruppi
    fastTitle:              "Riordino e gruppi",
    fastIntro:              "Un gruppo è un blocco unico nell'ordine di lettura: per riordinare gli elementi all'interno di un gruppo occorre prima separarlo. I pulsanti 1 e 4 salvano e poi ricostruiscono i gruppi.",
    btnFastReorder:         "3) Riordina la selezione",
    btnAlignZOrder:         "Allinea Construction RO al Tag RO (sperimentale)",
    btnFastSaveGroups:      "1) Salva i gruppi",
    btnFastUngroupAll:      "2) Separa tutti i gruppi",
    btnFastRegroup:         "4) Raggruppa dal salvataggio",
    fastNoSelection:        "Selezionare almeno 2 oggetti.",
    fastSingleTarget:       "La selezione corrisponde a un solo oggetto/gruppo. Selezionare almeno 2 oggetti indipendenti.",
    fastReordered:          "{count} oggetto/i riordinato/i.",
    fastReorderSkipped:     "Alcuni oggetti sono stati ignorati (genitore/livello diverso o tipo non supportato).",
    fastGroupsSaved:        "{count} gruppo/i salvato/i.",
    fastNoGroupsSaved:      "Nessun gruppo salvato per questo documento.",
    fastUngrouped:          "{count} gruppo/i separato/i.",
    fastRegrouped:          "{count} gruppo/i ricostituito/i.",
    alignDone:              "{count} oggetto/i riordinato/i secondo il Tag RO.",
    alignLayersWarning:     "Nota: gli oggetti si trovano su più livelli; l'ordine tra i livelli segue sempre la pila dei livelli.",
    articleCreated:         "Articolo \"{name}\" creato con {count} oggetto/i.",
    articleMembersAdded:    "{count} oggetto/i aggiunto/i all'articolo \"{name}\".",

    // Sezioni artefatti e testi alternativi
    artifactTitle:          "Artefatti",
    artifactPreviewTitle:   "Anteprima artefatti",
    altTextTitle:           "Testi alternativi",
    markupTitle:            "Marcatura HTML",
    btnSetArtifact:         "Definisci come artefatto",
    btnUnsetArtifact:       "Rimuovi il tag artefatto",
    btnToggleArtifacts:     "Nascondi/mostra gli artefatti",
    btnMoveArtifacts:       "Sposta gli artefatti sul livello [Artifacts]",
    btnRestoreArtifacts:    "Ripristina i livelli originali",
    btnShowAltText:         "Mostra i testi alternativi",
    btnHideAltText:         "Nascondi i testi alternativi",
    btnEditAltText:         "Modifica il testo alternativo",
    btnShowMarkup:          "Mostra la marcatura HTML",
    btnHideMarkup:          "Nascondi la marcatura HTML",
    altEditSave:            "Salva",
    altEditCancel:          "Annulla",
    altEditApplied:         "Testo alternativo salvato.",
    altEditArtifactRemoved: "Il tag artefatto è stato rimosso affinché il testo alternativo venga letto.",
    altEditNoTarget:        "Selezionare prima un oggetto nel documento.",
    markupDrawn:            "Livello [Markup] disegnato: {count} paragrafo/i.",
    markupDeleted:          "Livello [Markup] eliminato.",
    artifactHint:           "Gli artefatti sono esclusi da tutti gli ordini di lettura e nascosti nelle anteprime.",
    artifactsSet:           "{count} oggetto/i definito/i come artefatto.",
    artifactsUnset:         "Tag artefatto rimosso da {count} oggetto/i.",
    artifactsHidden:        "{count} artefatto/i nascosto/i.",
    artifactsShown:         "{count} artefatto/i visualizzato/i.",
    artifactsNone:          "Nessun artefatto in questo documento.",
    artifactsMoved:         "{count} artefatto/i spostato/i su [Artifacts].",
    artifactsMoveSkipped:   "{count} ignorato/i (all'interno di un gruppo — separare prima il gruppo).",
    artifactsRestored:      "{count} artefatto/i ripristinato/i sul livello originale.",
    artifactsNoMoves:       "Niente da ripristinare per questo documento.",
    altTextDrawn:           "Livello [Alt Text] disegnato: {count} immagine/i, {missing} senza testo alternativo.",
    altTextDeleted:         "Livello [Alt Text] eliminato.",
    altMissing:             "ALT MANCANTE",
    altDecorative:          "Decorativo",
    altExternal:            "Alt ({source})",

    // Selettore di lingua e informazioni
    langTitle:              "Lingua del plugin",
    langAuto:               "Auto (lingua di InDesign)",
    aboutTitle:             "Informazioni",
    aboutText:              "Questo strumento aiuta a costruire e verificare i due ordini di lettura di un PDF accessibile: il Tag RO (ordine del pannello Articoli, richiesto da PDF/UA, seguito dagli screen reader conformi) e la Construction RO (ordine di impilamento dei livelli, letto dal basso verso l'alto, seguito da reflow e lettori semplici). Procedura consigliata: 1. controllare l'anteprima pagina per pagina · 2. riordinare la selezione (separando prima i gruppi se necessario) · 3. contrassegnare gli artefatti e completare i testi alternativi · 4. verificare con i livelli di controllo, poi eliminarli prima dell'esportazione. Sviluppato da SZH/CSPS con il supporto dell'IA.",

    // Suggerimenti
    tipPreviewTag:          "Anteprima dell'ordine di lettura del pannello Articoli (seguito dagli screen reader conformi).",
    tipPreviewConstruction: "Anteprima dell'ordine della pila dei livelli, letto dal basso verso l'alto (seguito da reflow e lettori semplici).",
    tipNavPrev:             "Seleziona l'elemento precedente dell'ordine di lettura.",
    tipNavNext:             "Seleziona l'elemento successivo dell'ordine di lettura.",
    tipFastReorder:         "Passaggio 3 — utilizzabile anche da solo: selezionare gli oggetti con Maiusc-clic nell'ordine di lettura desiderato (primo cliccato = letto per primo), poi fare clic qui. La pila dei livelli e il pannello Articoli vengono aggiornati.",
    tipAlignZOrder:         "Nessuna selezione necessaria: riordina tutti gli elementi degli articoli affinché la Construction RO segua il Tag RO. Può modificare le sovrapposizioni visive — verificare la pagina dopo.",
    tipSaveGroups:          "Passaggio 1 del flusso con i gruppi: memorizza i gruppi attuali prima di separarli (questo documento, solo questa sessione).",
    tipUngroupAll:          "Passaggio 2: separa tutti i gruppi per riordinare ogni oggetto singolarmente (un gruppo è un blocco unico nell'ordine di lettura).",
    tipRegroup:             "Passaggio 4, dopo il riordino: ricostruisce i gruppi esattamente come salvati al passaggio 1.",
    tipSetArtifact:         "Contrassegna la selezione come artefatto: esclusa dalla struttura e da tutti gli ordini di lettura.",
    tipUnsetArtifact:       "Ripristina l'opzione di esportazione \"In base all'oggetto\" sulla selezione.",
    tipToggleArtifacts:     "Nasconde o mostra tutti gli artefatti del documento.",
    tipMoveArtifacts:       "Sposta gli artefatti sul livello [Artifacts] mantenendo il loro ordine di impilamento.",
    tipRestoreArtifacts:    "Riporta gli artefatti sui livelli originali.",
    tipEditAltText:         "Modifica il testo alternativo dell'oggetto selezionato direttamente nel pannello.",
    tipToggleAltText:       "Disegna/elimina il livello [Alt Text]: ogni immagine etichettata con il suo testo alternativo, mancanti in rosso.",
    tipToggleMarkup:        "Disegna/elimina il livello [Markup]: ogni paragrafo etichettato con il tag di esportazione PDF (<P> per impostazione predefinita)."
  }
};
